// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmt0iP31A8avnDfGlGtrUTeexfzDyQ3mY',
    appId: '1:721921826972:web:04562512e6839c6edccd59',
    messagingSenderId: '721921826972',
    projectId: 'mobileappproject-289f4',
    authDomain: 'mobileappproject-289f4.firebaseapp.com',
    storageBucket: 'mobileappproject-289f4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtCTzQlVE1pv0OOqmluIDIGniWKsCMmuE',
    appId: '1:721921826972:android:2a9b36e03875e698dccd59',
    messagingSenderId: '721921826972',
    projectId: 'mobileappproject-289f4',
    storageBucket: 'mobileappproject-289f4.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmt0iP31A8avnDfGlGtrUTeexfzDyQ3mY',
    appId: '1:721921826972:web:02d3805df66d2cfbdccd59',
    messagingSenderId: '721921826972',
    projectId: 'mobileappproject-289f4',
    authDomain: 'mobileappproject-289f4.firebaseapp.com',
    storageBucket: 'mobileappproject-289f4.firebasestorage.app',
  );
}
